### ISSUE TITLE
Script requires authentication even when not required by Transmission

### ISSUE THREAD

**Issue by faust64** [megazirt/nagios-plugin-transmission#1]
fyi, having a bunch of torrents already, several matches your grep statement.
I had to add some tail -1 to get the probe working.

Also, I removed the authentication part. Of course it is relevant when you're querying your seedbox from a remote host. Yet configuring transmission to listen on 127.0.0.1, I'm used to set it up without authentication (actually done by nginx/whatever frontend/...).

Anyway, thanks, and nice work.

**Comment by percz** [comment]
Thanks!
It's been a long time since you posted, but at some point I'll get around to fixing this! I've recently started changing from Nagios to Icinga, and got a few scripts to update and probs publish.
